package com.cyanbirds.yljy.entity;

// Generated 2016-2-12 19:55:00 by Hibernate Tools 3.4.0.CR1

/**
 * Captcha generated by hbm2java
 */
public class ShowClient implements java.io.Serializable {

	public Integer id;
	/**
	 * 0:不显示  1：显示
	 */
	public boolean isShowVip; //vip
	/**
	 * 0:不显示  1：显示
	 */
	public boolean isShowDownloadVip; //下载赚钱
	/**
	 * 0:不显示  1：显示
	 */
	public boolean isShowGold; //金币
	/**
	 * 0:不显示  1：显示
	 */
	public boolean isShowLovers; //红娘服务
	/**
	 * 0:不显示  1：显示
	 */
	public boolean isShowVideo; //视频
	/**
	 * 0:不显示  1：显示
	 */
	public boolean isPushMsg; //是否推送消息
	/**
	 * 0:不显示  1：显示
	 */
	public boolean isShowMap; //地图
	/**
	 * 0:不显示  1：显示
	 */
	public boolean isShowVoip; //电话
	/**
	 * 0:不显示  1：显示
	 */
	public boolean isShowRpt; //红包
	/**
	 * 0:不显示  1：显示
	 */
	public boolean isShowTd; //收取红包跳转到vip界面还是downloadvip界面
	/**
	 * 0:不显示  1：显示
	 */
	public boolean isShowAppointment; //是否显示约会
	
	/**渠道名**/
	public String channel;

}
